server:
  port: 8867
 
zuul:
  routes:
    order:
      path: /order/**
      #超时配置说明：
      #如果路由方式是serviceId的方式，配置为：zuul:routes:order:serviceId，那么ribbon的超时配置生效（order-service:ribbon:ReadTimeout）
      #如果如果是url的方式，配置为：zuul:routes:order:url，则zuul.host开头的超时生效。
      serviceId: order-service
      #url: http://localhost:8763
    user:
      path: /user/**
      serviceId: user-service
    biz:
      path: /biz/**
      serviceId: biz-service
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000

#ribbon的请求时间必须要设置，因为zuul路由用的是ribbon
ribbon:
  ReadTimeout:  20000
  ConnectTimeout:  20000
#熔断器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

order-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
user-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
biz-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000

spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

test-string: 改后的gateway2222
